<!DOCTYPE html>
<html>
	<head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">      
        <title>Destroy The Cutie</title>
        <meta name="description" content="Browse over 300 000 of the best porn galleries for FREE! Hot sex pictures sorted by categories, hand picked and updated daily.">
		<meta name="hubtraffic-domain-validation" content="dc3b312e06aa01b1" />
		<meta name="xhamster-site-verification" content="dcb793db0e4ba8eb59edaea6452e735b"/>
		<link rel="stylesheet" type="text/css" href="/css/styles.css">
		<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
		<script src="http://cdn.jsdelivr.net/masonry/2.1.08/jquery.masonry.min.js"></script>
		<script src="http://cdn.jsdelivr.net/jquery.lazyload/1.8.4/jquery.lazyload.js" ></script>
		<!--<script src="https://npmcdn.com/masonry-layout@4.0/dist/masonry.pkgd.min.js"></script>-->
		<script src="/js/imagesLoad.js"></script>
        <!--<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">-->
        <!--<link href="/favicon/ppics_152x152_w.png" sizes="152x152" rel="apple-touch-icon-precomposed">
        <link href="/favicon/ppics_144x144_w.png" sizes="144x144" rel="apple-touch-icon-precomposed">
        <link href="/favicon/ppics_120x120_w.png" sizes="120x120" rel="apple-touch-icon-precomposed">
        <link href="/favicon/ppics_114x114_w.png" sizes="114x114" rel="apple-touch-icon-precomposed">
        <link href="/favicon/ppics_72x72_w.png" sizes="72x72" rel="apple-touch-icon-precomposed">
        <link href="/favicon/ppics_57x57_w.png" rel="apple-touch-icon-precomposed">-->
    </head>
	<body>
		<h2 class="header-title">WANNA SEE THOSE CUTIES DESTROYED?</h2>
		<div id="tiles" class="grid">
			<?php //class="grid js-masonry" data-masonry-options='{ "itemSelector": ".grid-item", "columnWidth": 300,"gutter":5,"fitWidth":true }'?>        
             <div class="logo-main thumbwook grid-item">
                        <div class="logo">
                            <a href="/">
                                <img class="logo-desctop1" src="/images/dst/destroy_cutie.png" width="300" alt="Destroy The Cutie" >
                            </a>
                        </div>
                    </div>
					<?php 
					$iter = 1;
					foreach ($content as $item){ ?>
						<div class="thumbwook grid-item">
							<a class="rel-link" target="_blank" href="<?php echo $item['link'];?>">
								
								<img class="<?php echo ($iter>=10)?'not-loaded':'';?>" src="<?php echo $cdn_url.$item['image_url'];?>" data-original="<?php echo $cdn_url.$item['image_url'];?>">
							</a>
						</div>
					<?php 
					$iter++;
					}?>				
		</div>
		
		<?php if ($isShowPagination){?>
		<div class="pagination">
			<a <?php if($cur_page==0){echo 'class="current"';}?> href="/">
				<?php echo ($cur_page==0)?'1':'First'?>
			</a>
			
			<?php if($cur_page-1>0 and $cur_page-1<($pages_count-1)){?>
				<a href="/<?php echo $cur_page-1?>"><?php echo $cur_page?></a>
			<?php }?>
			
			<?php if($cur_page>0 and $cur_page<($pages_count-1)){?>
				<a class="current" href="/<?php echo $cur_page?>"><?php echo $cur_page+1?></a>
			<?php }?>
				
			<?php if($cur_page+1<($pages_count-1)){?>
				<a href="/<?php echo $cur_page+1?>"><?php echo $cur_page+2?></a>
			<?php }?>
				
			<a <?php if($cur_page==($pages_count-1)){echo 'class="current"';}?> href="/<?php echo $pages_count-1?>">
				<?php echo ($cur_page==($pages_count-1))?$pages_count:'Last'?>
			</a>
			</div>		
		<?php }?>		
		<script>
			var $container = $('.grid');
			$container.imagesLoaded(function(){
				$container.masonry({
					gutter: 5,
					isFitWidth:true
				});
				$('.not-loaded').lazyload({
					effect: 'fadeIn',
					load: function() {
						// Disable trigger on this image
						$(this).removeClass("not-loaded");
						$container.masonry('reload',{isFitWidth:true});
					}
    });
			});
		</script>
		<script>
			(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
			})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

			ga('create', 'UA-80387121-1', 'auto');
			ga('send', 'pageview');

</script>
	</body>
</html>
